name: check-translations

on:
  push:
    branches:
      - master
      - development
      - release
  pull_request:

jobs:
  check-translations:
    services:
    mongodb:
      image: mongo:4.2.6
      ports:
        - 27017/tcp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.6.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.6.x'
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: install dependencies
        run: yarn install
      - run: yarn blank-state
      - run: yarn migrate
      - run: yarn check-translations
